# Generated by Django 5.2.5 on 2025-10-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
