# Generated by Django 5.2.5 on 2025-10-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0002_formfield_is_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='custm_sent_to_admin',
            field=models.BooleanField(default=False, help_text='Whether this record has been sent to admin'),
        ),
    ]
