# Generated by Django 5.2.5 on 2025-10-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0003_architecture_custm_sent_to_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Completed')], default=0, help_text='Status of the record: 0=Pending, 1=Accepted, 2=Rejected, 3=Completed'),
        ),
    ]
