# Generated by Django 5.2.5 on 2025-12-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0005_client_portfolioitem_service_statistic_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
