# Generated by Django 5.2.5 on 2025-12-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0006_alter_testimonial_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=10),
        ),
    ]
