# Generated by Django 5.2.5 on 2026-02-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0007_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldresponse',
            name='value_alphanumeric',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldresponse',
            name='value_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fieldresponse',
            name='value_phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('image', 'Image'), ('alphanumeric', 'Alphanumeric'), ('email', 'Email ID'), ('phonenumber', 'Phone Number')], max_length=20),
        ),
    ]
